package com.rindev.chat;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real HTTP and MySQL lifecycle checks. Enable only against an explicitly
 * selected test database.
 * Every mutation and cleanup is scoped to accounts generated by the current
 * test.
 */
@SpringBootTest(classes = ChatApplication.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@EnabledIfEnvironmentVariable(named = "CHAT_WRITE_TESTS", matches = "true")
class AuthApiIntegrationTest {

    private static final String PASSWORD = "Integration-" + UUID.randomUUID();
    private static final HttpClient HTTP = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(10)).build();

    private final List<Identity> ownedAccounts = new ArrayList<>();

    @Autowired
    private JdbcTemplate jdbc;

    @Autowired
    private ObjectMapper json;

    @Autowired
    private PasswordEncoder passwords;

    @Value("${local.server.port}")
    private int port;

    @DynamicPropertySource
    static void signingKey(DynamicPropertyRegistry properties) {
        byte[] key = new byte[32];
        new SecureRandom().nextBytes(key);
        String secret = Base64.getEncoder().encodeToString(key);
        properties.add("security.jwt.secret", () -> secret);
        properties.add("security.jwt.access-token-ttl", () -> "15m");
    }

    @AfterEach
    void removeOnlyAccountsOwnedByThisTest() {
        for (Identity account : ownedAccounts) {
            // The schema cascades deletion to settings and refresh tokens.
            jdbc.update("DELETE FROM users WHERE username = ? AND email = ?",
                    account.username(), account.email());
        }
    }

    @Test
    void registrationPersistsHashedCredentialsAndDefaultSettingsAndAuthenticatesMe() throws Exception {
        Identity account = identity();
        JsonNode auth = register(account);
        long userId = auth.path("user").path("id").asLong();

        assertThat(auth.path("tokenType").stringValue()).isEqualTo("Bearer");
        assertThat(auth.path("expiresIn").asLong()).isEqualTo(900);
        assertThat(Instant.parse(auth.path("refreshExpiresAt").stringValue())).isAfter(Instant.now());
        assertThat(auth.path("refreshToken").stringValue()).matches("[A-Za-z0-9_-]{43}");
        assertSafeSelf(auth.path("user"), account, userId);

        Map<String, Object> user = jdbc.queryForMap("SELECT * FROM users WHERE id = ?", userId);
        String hash = (String) user.get("password_hash");
        assertThat(hash).startsWith("$2").isNotEqualTo(PASSWORD);
        assertThat(passwords.matches(PASSWORD, hash)).isTrue();
        assertThat(user.get("status")).isEqualTo("offline");
        assertThat(user.get("created_at")).isNotNull();

        jdbc.query("SELECT * FROM user_settings WHERE user_id = ?", result -> {
            assertThat(result.next()).isTrue();
            assertThat(result.getString("theme")).isEqualTo("system");
            for (String field : List.of("message_notifications", "group_notifications",
                    "reaction_notifications", "read_receipts")) {
                assertThat(result.getBoolean(field)).as(field).isTrue();
            }
            for (String field : List.of("last_seen_privacy", "profile_photo_privacy", "group_add_privacy")) {
                assertThat(result.getString(field)).as(field).isEqualTo("everyone");
            }
            assertThat(result.next()).isFalse();
            return null;
        }, userId);

        assertThat(jdbc.queryForObject("SELECT token_hash FROM refresh_tokens WHERE user_id = ?",
                String.class, userId)).isEqualTo(digest(auth.path("refreshToken").stringValue()));
        JsonNode current = success(request("GET", "/api/v1/auth/me?userId=9223372036854775807",
                null, auth.path("accessToken").stringValue()), 200);
        assertSafeSelf(current, account, userId);
        assertThat(current.toString()).doesNotContain(hash, PASSWORD, "password", "tokenHash", "refreshToken");
    }

    @Test
    void duplicateUsernameAndEmailUseMysqlCaseInsensitiveUniquenessWithoutPartialAccounts() throws Exception {
        Identity original = identity();
        JsonNode auth = register(original);
        Identity other = identity();

        assertError(request("POST", "/api/v1/auth/register",
                registration(original.username(), other.email()), null), 409);
        assertError(request("POST", "/api/v1/auth/register",
                registration(original.username().toUpperCase(Locale.ROOT), other.email()), null), 409);
        assertError(request("POST", "/api/v1/auth/register",
                registration(other.username(), original.email().toUpperCase(Locale.ROOT)), null), 409);

        assertThat(count("SELECT COUNT(*) FROM users WHERE username = ?", other.username())).isZero();
        long userId = auth.path("user").path("id").asLong();
        assertThat(count("SELECT COUNT(*) FROM user_settings WHERE user_id = ?", userId)).isEqualTo(1);
        assertThat(count("SELECT COUNT(*) FROM refresh_tokens WHERE user_id = ?", userId)).isEqualTo(1);
    }

    @Test
    void simultaneousRegistrationCreatesExactlyOneCompleteAccount() throws Exception {
        Identity account = identity();
        HttpRequest request = buildRequest("POST", "/api/v1/auth/register", registration(account), null);
        List<HttpResponse<String>> responses = concurrently(request, request);

        assertThat(responses).extracting(HttpResponse::statusCode).containsExactlyInAnyOrder(201, 409);
        JsonNode auth = success(responses.stream().filter(response -> response.statusCode() == 201)
                .findFirst().orElseThrow(), 201);
        long userId = auth.path("user").path("id").asLong();
        assertThat(count("SELECT COUNT(*) FROM users WHERE username = ?", account.username())).isEqualTo(1);
        assertThat(count("SELECT COUNT(*) FROM user_settings WHERE user_id = ?", userId)).isEqualTo(1);
        assertThat(count("SELECT COUNT(*) FROM refresh_tokens WHERE user_id = ?", userId)).isEqualTo(1);
    }

    @Test
    void loginVerifiesPasswordAndCreatesAnIndependentSession() throws Exception {
        Identity account = identity();
        JsonNode registered = register(account);
        JsonNode loggedIn = success(request("POST", "/api/v1/auth/login",
                Map.of("username", account.username(), "password", PASSWORD), null), 200);
        long userId = registered.path("user").path("id").asLong();

        assertSafeSelf(loggedIn.path("user"), account, userId);
        assertThat(loggedIn.path("refreshToken").stringValue())
                .isNotEqualTo(registered.path("refreshToken").stringValue());
        assertThat(count("SELECT COUNT(*) FROM refresh_tokens WHERE user_id = ?", userId)).isEqualTo(2);
        assertSafeSelf(success(request("GET", "/api/v1/auth/me", null,
                loggedIn.path("accessToken").stringValue()), 200), account, userId);
    }

    @Test
    void wrongPasswordAndUnknownUsernameReturnTheSameSafeFailureAndNoNewTokens() throws Exception {
        Identity account = identity();
        JsonNode registered = register(account);
        String rejectedPassword = "Wrong-" + UUID.randomUUID();
        JsonNode wrong = assertError(request("POST", "/api/v1/auth/login",
                Map.of("username", account.username(), "password", rejectedPassword), null), 401);
        JsonNode unknown = assertError(request("POST", "/api/v1/auth/login",
                Map.of("username", identity().username(), "password", rejectedPassword), null), 401);

        assertThat(wrong.path("code")).isEqualTo(unknown.path("code"));
        assertThat(wrong.path("message")).isEqualTo(unknown.path("message"));
        assertThat(wrong.toString()).doesNotContain(account.username(), PASSWORD, rejectedPassword);
        assertThat(count("SELECT COUNT(*) FROM refresh_tokens WHERE user_id = ?",
                registered.path("user").path("id").asLong())).isEqualTo(1);
    }

    @ParameterizedTest(name = "registration rejects invalid {0}")
    @MethodSource("invalidRegistrationFields")
    void invalidRegistrationIsRejectedBeforeAnyPersistence(String field, String invalid) throws Exception {
        Identity account = identity();
        Map<String, Object> body = new HashMap<>(registration(account));
        body.put(field, invalid);

        JsonNode error = assertError(request("POST", "/api/v1/auth/register", body, null), 400);
        assertThat(error.toString()).doesNotContain(PASSWORD, "passwordHash", "rejectedValue");
        assertThat(count("SELECT COUNT(*) FROM users WHERE username = ? OR email = ?",
                account.username(), account.email())).isZero();
    }

    static Stream<Arguments> invalidRegistrationFields() {
        return Stream.of(
                Arguments.of("name", " "),
                Arguments.of("name", "a".repeat(101)),
                Arguments.of("username", "bad username"),
                Arguments.of("username", "a".repeat(51)),
                Arguments.of("email", "not-an-email"),
                Arguments.of("password", "short"),
                Arguments.of("password", "a".repeat(73)),
                Arguments.of("password", "é".repeat(37)));
    }

    @Test
    void malformedJsonAndMissingCredentialsReturnSafeClientErrors() throws Exception {
        HttpRequest malformed = HttpRequest.newBuilder(URI.create(baseUrl() + "/api/v1/auth/register"))
                .timeout(Duration.ofSeconds(15)).header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString("{\"password\":\"private-malformed-value\""))
                .build();
        JsonNode error = assertError(HTTP.send(malformed, HttpResponse.BodyHandlers.ofString()), 400);
        assertThat(error.toString()).doesNotContain("private-malformed-value", "JsonParseException");
        assertError(request("POST", "/api/v1/auth/login", Map.of(), null), 400);
        assertError(request("POST", "/api/v1/auth/refresh", Map.of(), null), 400);
    }

    @Test
    void refreshRotatesPersistedHashAndRejectsThePreviousCredential() throws Exception {
        JsonNode registered = register(identity());
        long userId = registered.path("user").path("id").asLong();
        String oldToken = registered.path("refreshToken").stringValue();

        JsonNode renewed = success(refresh(oldToken), 200);
        String newToken = renewed.path("refreshToken").stringValue();
        assertThat(newToken).isNotEqualTo(oldToken);
        assertThat(renewed.path("user").path("id").asLong()).isEqualTo(userId);
        assertThat(count("SELECT COUNT(*) FROM refresh_tokens WHERE user_id = ?", userId)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT token_hash FROM refresh_tokens WHERE user_id = ?",
                String.class, userId)).isEqualTo(digest(newToken));
        assertError(refresh(oldToken), 401);
        success(request("GET", "/api/v1/auth/me", null, renewed.path("accessToken").stringValue()), 200);
        success(refresh(newToken), 200);
    }

    @Test
    void concurrentRefreshConsumesTheCredentialExactlyOnce() throws Exception {
        JsonNode registered = register(identity());
        String token = registered.path("refreshToken").stringValue();
        HttpRequest renewal = buildRequest("POST", "/api/v1/auth/refresh", Map.of("refreshToken", token), null);

        List<HttpResponse<String>> responses = concurrently(renewal, renewal);
        assertThat(responses).extracting(HttpResponse::statusCode).containsExactlyInAnyOrder(200, 401);
        JsonNode winner = success(responses.stream().filter(response -> response.statusCode() == 200)
                .findFirst().orElseThrow(), 200);
        assertError(refresh(token), 401);
        success(refresh(winner.path("refreshToken").stringValue()), 200);
        assertThat(count("SELECT COUNT(*) FROM refresh_tokens WHERE user_id = ?",
                registered.path("user").path("id").asLong())).isEqualTo(1);
    }

    @Test
    void expiredRefreshCannotRenewOrChangeItsStoredCredential() throws Exception {
        JsonNode registered = register(identity());
        String token = registered.path("refreshToken").stringValue();
        long userId = registered.path("user").path("id").asLong();
        assertThat(jdbc.update("""
                UPDATE refresh_tokens SET expires_at = UTC_TIMESTAMP(6) - INTERVAL 1 SECOND
                WHERE user_id = ? AND token_hash = ?
                """, userId, digest(token))).isEqualTo(1);

        assertError(refresh(token), 401);
        assertThat(jdbc.queryForObject("SELECT token_hash FROM refresh_tokens WHERE user_id = ?",
                String.class, userId)).isEqualTo(digest(token));
    }

    @Test
    void unknownRefreshCredentialIsRejectedWithoutEchoingIt() throws Exception {
        String token = Base64.getUrlEncoder().withoutPadding()
                .encodeToString(UUID.randomUUID().toString().substring(0, 32).getBytes(StandardCharsets.US_ASCII));
        JsonNode error = assertError(refresh(token), 401);
        assertThat(error.toString()).doesNotContain(token);
    }

    @Test
    void logoutRevokesOnlyTheSelectedSessionAndIsIdempotent() throws Exception {
        Identity account = identity();
        JsonNode first = register(account);
        JsonNode second = success(request("POST", "/api/v1/auth/login",
                Map.of("username", account.username(), "password", PASSWORD), null), 200);
        String refreshToken = first.path("refreshToken").stringValue();
        String accessToken = first.path("accessToken").stringValue();
        Map<String, String> logout = Map.of("refreshToken", refreshToken);

        assertThat(request("POST", "/api/v1/auth/logout", logout, accessToken).statusCode()).isEqualTo(204);
        assertThat(request("POST", "/api/v1/auth/logout", logout, accessToken).statusCode()).isEqualTo(204);
        assertThat(jdbc.queryForObject("SELECT revoked_at IS NOT NULL FROM refresh_tokens WHERE token_hash = ?",
                Boolean.class, digest(refreshToken))).isTrue();
        assertError(refresh(refreshToken), 401);
        success(refresh(second.path("refreshToken").stringValue()), 200);
        // Access JWTs remain valid until expiry; logout revokes the chosen renewable
        // session.
        success(request("GET", "/api/v1/auth/me", null, accessToken), 200);
    }

    @Test
    void logoutRequiresAuthenticationAndCannotRevokeAnotherUsersSession() throws Exception {
        JsonNode owner = register(identity());
        JsonNode other = register(identity());
        Map<String, String> logout = Map.of("refreshToken", owner.path("refreshToken").stringValue());

        assertError(request("POST", "/api/v1/auth/logout", logout, null), 401);
        assertError(request("POST", "/api/v1/auth/logout", logout, other.path("accessToken").stringValue()), 403);
        success(refresh(owner.path("refreshToken").stringValue()), 200);
        success(refresh(other.path("refreshToken").stringValue()), 200);
    }

    @Test
    void currentUserRequiresAuthentication() throws Exception {
        assertError(request("GET", "/api/v1/auth/me", null, null), 401);
    }

    private Identity identity() {
        String username = "auth_it_" + UUID.randomUUID().toString().replace("-", "");
        Identity account = new Identity(username, username + "@example.test");
        ownedAccounts.add(account);
        return account;
    }

    private Map<String, Object> registration(Identity account) {
        return registration(account.username(), account.email());
    }

    private Map<String, Object> registration(String username, String email) {
        return Map.of("name", "Integration User", "username", username, "email", email, "password", PASSWORD);
    }

    private JsonNode register(Identity account) throws Exception {
        return success(request("POST", "/api/v1/auth/register", registration(account), null), 201);
    }

    private HttpResponse<String> refresh(String token) throws Exception {
        return request("POST", "/api/v1/auth/refresh", Map.of("refreshToken", token), null);
    }

    private HttpResponse<String> request(String method, String path, Object body, String token) throws Exception {
        return HTTP.send(buildRequest(method, path, body, token), HttpResponse.BodyHandlers.ofString());
    }

    private HttpRequest buildRequest(String method, String path, Object body, String token) {
        var builder = HttpRequest.newBuilder(URI.create(baseUrl() + path)).timeout(Duration.ofSeconds(30));
        if (token != null) {
            builder.header("Authorization", "Bearer " + token);
        }
        if (body == null) {
            builder.method(method, HttpRequest.BodyPublishers.noBody());
        } else {
            builder.header("Content-Type", "application/json")
                    .method(method, HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));
        }
        return builder.build();
    }

    private List<HttpResponse<String>> concurrently(HttpRequest first, HttpRequest second) throws Exception {
        var one = HTTP.sendAsync(first, HttpResponse.BodyHandlers.ofString());
        var two = HTTP.sendAsync(second, HttpResponse.BodyHandlers.ofString());
        CompletableFuture.allOf(one, two).get(40, TimeUnit.SECONDS);
        return List.of(one.join(), two.join());
    }

    private JsonNode success(HttpResponse<String> response, int expectedStatus) {
        assertThat(response.statusCode()).isEqualTo(expectedStatus);
        assertThat(response.headers().firstValue("set-cookie")).isEmpty();
        JsonNode envelope = json.readTree(response.body());
        assertThat(envelope.path("success").asBoolean()).isTrue();
        assertThat(envelope.path("code").stringValue()).isNotBlank();
        assertThat(envelope.path("message").stringValue()).isNotBlank();
        assertThat(Instant.parse(envelope.path("timestamp").stringValue())).isBeforeOrEqualTo(Instant.now());
        assertThat(envelope.has("data")).isTrue();
        return envelope.path("data");
    }

    private JsonNode assertError(HttpResponse<String> response, int expectedStatus) {
        assertThat(response.statusCode()).isEqualTo(expectedStatus);
        assertThat(response.headers().firstValue("content-type").orElse("")).contains("application/json");
        JsonNode error = json.readTree(response.body());
        assertThat(error.path("success").asBoolean()).isFalse();
        assertThat(error.path("code").stringValue()).isNotBlank();
        assertThat(error.path("message").stringValue()).isNotBlank();
        assertThat(Instant.parse(error.path("timestamp").stringValue())).isBeforeOrEqualTo(Instant.now());
        assertThat(error.has("trace")).isFalse();
        assertThat(error.has("exception")).isFalse();
        assertThat(response.body()).doesNotContain("passwordHash", "password_hash", "java.", "org.hibernate",
                "SQLIntegrityConstraintViolationException");
        return error;
    }

    private void assertSafeSelf(JsonNode user, Identity account, long id) {
        assertThat(user.path("id").asLong()).isEqualTo(id);
        assertThat(user.path("username").stringValue()).isEqualTo(account.username());
        assertThat(user.path("email").stringValue()).isEqualTo(account.email());
        assertThat(user.path("name").stringValue()).isEqualTo("Integration User");
        assertThat(user.has("password")).isFalse();
        assertThat(user.has("passwordHash")).isFalse();
        assertThat(user.has("userSettings")).isFalse();
        assertThat(user.has("refreshTokens")).isFalse();
    }

    private long count(String sql, Object... parameters) {
        return jdbc.queryForObject(sql, Long.class, parameters);
    }

    private String digest(String token) throws Exception {
        return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256")
                .digest(token.getBytes(StandardCharsets.US_ASCII)));
    }

    private String baseUrl() {
        return "http://127.0.0.1:" + port;
    }

    private record Identity(String username, String email) {
    }
}
